var STATES = {
        PLANE_FLYING: 1,
        COUNTDOWN: 2,
        GAMEOVER: 3,
        WELCOME: 4
    },
    COUNTDOWN = 3,
    CLOUDS = 20,
    RUNWAY_WIDTH = 700,
    RUNWAY_DISTANCE = 1200,
    MIN_PLANE_VELOCITY = 150;
